### ISSUE TITLE
Request: Add X570-F board

### ISSUE THREAD

**Issue by olehj** [zeule/asus-ec-sensors#10]
Board: "ROG STRIX X570-F GAMING" - uses the same \\AMW0.ASMX as the other boards

Sensors verified to work:
SENSOR_SET_TEMP_CHIPSET_CPU_MB
SENSOR_TEMP_T_SENSOR
SENSOR_FAN_CHIPSET

asus-ec-sensors-isa-0000
Adapter: ISA adapter
Chipset:     2672 RPM
Chipset:      +61.0°C  
CPU:          +34.0°C  
Motherboard:  +35.0°C  
T_Sensor:     +30.0°C  
VRM:           +0.0°C  
CPU:           0.00 A

**Comment by zeule** [comment]
Thank you! The VRM temperature sensors shows 0 in your example. Shouldn't it be removed? Maybe you can test with ASUS software (or another software like HWINFO) on Windows?

**Comment by olehj** [comment]
I posted the results with a direct copy from the E-board just modifying it to F. There's no VRM temp nor CPU current as far as I could see in HWINFO or even the UEFI directly.

So the three sensor variables in the initial posts seems to be the working ones (I used the review2 branch).

**Comment by zeule** [comment]
OK, so we remove the VRM temp. But I'm surprised there is no CPU current sensor. Could you, please, test under a high CPU load?

**Comment by olehj** [comment]
No info (still 0A) using Prime95 full load on all 12/24 cores/ht. AMD 5900X

**Comment by olehj** [comment]
...dunno if it requires some C-states or other ACPI features from UEFI which I might have disabled?

**Comment by zeule** [comment]
Thank you! I will add the board with the provided information.
