### ISSUE TITLE
License required for inclusion in distro package managers

### ISSUE THREAD

**Issue by NickHu** [zeule/asus-ec-sensors#4]
This is great work, thank you for your efforts. I would like to package this up for nixos, much like how [asus-wmi-sensors](https://github.com/electrified/asus-wmi-sensors) is already packaged so that users can simply include the module in their configurations, but the lack of a license in this repository precludes this. Could you please add one?

**Comment by zeule** [comment]
Ah, thank you, I forgot to add a license file. Done now.
